# Generated by Django 4.2.20 on 2025-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPomodoroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('completed_rounds', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailypomodorostats',
            constraint=models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_date_stats'),
        ),
    ]
